# Generated by Django 5.0.7 on 2024-07-28 19:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=120)),
                ('slug', models.SlugField()),
                ('desc_courte', models.TextField(blank=True, null=True)),
                ('desc_longue', models.TextField(blank=True, null=True)),
                ('prix', models.IntegerField()),
                ('qte', models.IntegerField(default=0)),
                ('disponible', models.BooleanField(default=True)),
                ('image_produit', models.ImageField(blank=True, null=True, upload_to='produit_image')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.categorie')),
            ],
        ),
    ]
