# Generated by Django 5.0.7 on 2024-07-31 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
