# Generated by Django 5.0.7 on 2024-08-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_shippingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='utilisateur',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='telephone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='ville',
            field=models.CharField(max_length=255),
        ),
    ]
