# Generated by Django 5.0.7 on 2024-08-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_utilisateur_shippingaddress_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image_similaire_1',
            field=models.ImageField(blank=True, null=True, upload_to='produit_image'),
        ),
        migrations.AddField(
            model_name='produit',
            name='image_similaire_2',
            field=models.ImageField(blank=True, null=True, upload_to='produit_image'),
        ),
        migrations.AddField(
            model_name='produit',
            name='image_similaire_3',
            field=models.ImageField(blank=True, null=True, upload_to='produit_image'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='qte',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
