# Generated by Django 5.0.7 on 2024-08-20 20:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_produit_image_similaire_1_produit_image_similaire_2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_disponible', models.IntegerField(default=0)),
                ('seuil_minimum', models.IntegerField(default=5)),
                ('emplacement_stock', models.CharField(blank=True, max_length=255, null=True)),
                ('produit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('type_vente', models.CharField(choices=[('en ligne', 'En Ligne'), ('en boutique', 'En Boutique')], max_length=20)),
                ('prix_unitaire', models.IntegerField()),
                ('total', models.IntegerField()),
                ('date_vente', models.DateTimeField(default=django.utils.timezone.now)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.produit')),
                ('vendeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
