# Generated by Django 5.0.7 on 2024-08-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_stock_vente'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='nom_client',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='numero_vente',
            field=models.CharField(default='DEFAULT_VALUE', max_length=100),
        ),
    ]
